create table if not exists public.orders (
	id bigint generated by default as identity primary key,
	user_id uuid,
	status text not null default 'carrinho' check (
		status in ('carrinho', 'pago', 'aguardando_pagamento', 'em_transporte', 'entregue')
	),
	total numeric(10,2) not null default 0 check (total >= 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_status_idx on public.orders(status);

create table if not exists public.order_items (
	id bigint generated by default as identity primary key,
	order_id bigint not null references public.orders(id) on delete cascade,
	product_id bigint not null references public.products(id),
	name text not null,
	price numeric(10,2) not null check (price >= 0),
	quantity integer not null check (quantity > 0),
	img text not null,
	category text not null,
	created_at timestamptz not null default now()
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);

create or replace function public.set_updated_at()
returns trigger as $$
begin
	new.updated_at = now();
	return new;
end;
$$ language plpgsql;

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();
