create table if not exists public.products (
	id bigint generated by default as identity primary key,
	name text not null,
	price numeric(10,2) not null check (price >= 0),
	category text not null,
	img text not null,
	badge text
);

insert into public.products (name, price, category, img, badge)
values
	('Camiseta Basica', 49.90, 'Roupas', '/products/camiseta.jpg', 'Mais vendido'),
	('Tenis Casual', 189.90, 'Calcados', '/products/tenis.jpg', 'Novo'),
	('Mochila Urban', 129.90, 'Acessorios', '/products/mochila.jpg', null)
on conflict do nothing;
